# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ../../build
TARGET = $(TARGETDIR)/NoreSources.Build.dll
OBJDIR = ../../obj/Debug/NoreSources.Build
  FLAGS = /noconfig
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

ifeq ($(config),release)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ../../build
TARGET = $(TARGETDIR)/NoreSources.Build.dll
OBJDIR = ../../obj/Release/NoreSources.Build
  FLAGS = /noconfig
  DEPENDS =
  REFERENCES = 
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef
endif

FLAGS += /t:library 
REFERENCES += /r:System.dll /r:Microsoft.Build.dll /r:Microsoft.Build.Utilities.v4.0.dll /r:Microsoft.Build.Framework.dll

SOURCES += \
	../../src/build/Logger.cs \

EMBEDFILES += \

RESPONSE += $(OBJDIR)/NoreSources.Build.rsp
SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

all: prebuild $(EMBEDFILES) $(COPYFILES) $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS) $(RESPONSE) | $(TARGETDIR)
	$(PRELINKCMDS)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) @$(RESPONSE) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(RESPONSE): NoreSources.Build.make
	@echo Generating response file
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f $(RESPONSE)
else
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\NoreSources.Build.rsp
endif
	@echo ../../src/build/Logger.cs >> $(RESPONSE)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)
