# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

ifeq ($(config),debug)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ../../bin/Debug
TARGET = $(TARGETDIR)/NotifyAndSearch.exe
OBJDIR = ../../obj/Debug/NotifyAndSearch
  FLAGS = /noconfig
  DEPENDS = ../../lib/Debug/NoreSources.SSDP.dll
  REFERENCES = /r:../../lib/Debug/NoreSources.SSDP.dll
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
	@echo Running postbuild commands
	cp -f ../../bin/lib/NoreSources.SSDP.dll ../../bin/Debug
endef
endif

ifeq ($(config),release)
  CSC = csc
  RESGEN = resgen
TARGETDIR = ../../bin/Release
TARGET = $(TARGETDIR)/NotifyAndSearch.exe
OBJDIR = ../../obj/Release/NotifyAndSearch
  FLAGS = /noconfig
  DEPENDS = ../../lib/Release/NoreSources.SSDP.dll
  REFERENCES = /r:../../lib/Release/NoreSources.SSDP.dll
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
	@echo Running postbuild commands
	cp -f ../../bin/lib/NoreSources.SSDP.dll ../../bin/Release
endef
endif

FLAGS += /t:exe 
REFERENCES += /r:System.dll /r:System.Net.Http.dll

SOURCES += \
	../../src/examples/NotifyAndSearch.cs \

EMBEDFILES += \

RESPONSE += $(OBJDIR)/NotifyAndSearch.rsp
SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

all: prebuild $(EMBEDFILES) $(COPYFILES) $(TARGET)

$(TARGET): $(SOURCES) $(EMBEDFILES) $(DEPENDS) $(RESPONSE) | $(TARGETDIR)
	$(PRELINKCMDS)
	$(SILENT) $(CSC) /nologo /out:$@ $(FLAGS) $(REFERENCES) @$(RESPONSE) $(patsubst %,/resource:%,$(EMBEDFILES))
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(RESPONSE): NotifyAndSearch.make
	@echo Generating response file
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f $(RESPONSE)
else
	$(SILENT) if exist $(RESPONSE) del $(OBJDIR)\NotifyAndSearch.rsp
endif
	@echo ../../src/examples/NotifyAndSearch.cs >> $(RESPONSE)

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)
